editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json
https://trello.com/c/OfSuTIGJ/839-left-click-for-context-menu
- Add translation click for menu item
- Select left click mode in edit menu and click workspace
=> translation click for menu item

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
=> Change name

editor/interface/en.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/t6SBGIvw
- Add share with friend button title
* Look in …
=> Feature - Share with friend button transaltion

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
[#856](https://trello.com/c/dJhtnQtv/856-create-a-button-for-generate-project-avatar)
- Add translation capture project avatar button 
https://user-images.githubusercontent.com/81544374/134313814-b8cd0ff2-8eee-4ba2-a2b1-6e5662304438.mov
=> add translation generate avatar button

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/dlsie3Ch
- Add missing blocks translate
* Look in …
=> Enhance - Add missing translate

editor/extensions/es.json, editor/extensions/fr.json, editor/interface/en.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
[#923](https://trello.com/c/7LqBaEVu/923-add-publish-to-friends)
- Add translation publish with friend button
https://user-images.githubusercontent.com/81544374/136187801-7a603939-b370-4e2a-9338-76dc580971a1.mov
=> add translation publish with friend button

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/LqjBnbZl
add communityObjectNotFound message
* Look in …
=> Add - community model message

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
[#1010](https://trello.com/c/LBVr93Nr/1010-a-new-3d-block-to-switch-to-full-screen)
- Handle switch to full screen block
https://user-images.githubusercontent.com/81544374/140897141-fd6770da-9f8a-457c-b78f-ef0aebf5cbb1.mov
=> translation switch screen block

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
Ref: https://trello.com/c/ebCvIwmH/1000-a-few-issues-with-widget-button
=> [Enhance Widget] Add please select msg for widget

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
Ref: https://trello.com/c/QQa9X8qE/997-2-new-blocks-for-3d-objects-for-properties
=> Add locale for d3 object property block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
Ref: https://trello.com/c/o16shkA9/975-collapsing-code-stack-doesnt-work-for-large-projects
=> Add collapse all stacks

editor/paint-editor/en.json, editor/paint-editor/es.json, editor/paint-editor/fr.json, editor/paint-editor/zh-cn.json, editor/paint-editor/zh-tw.json
[#775](https://trello.com/c/tebuwUUL/775-improve-2d-costume-editor-for-drawing-vector)
-Translation tooltip title rounded triangle , hexagon, pentagon, octagon 2D mode
=> translation 2D mode

editor/blocks/zh-tw.json
=> Fix DATA_SAVEDATA tw message

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
=> Add translation p2p

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
Ref: https://trello.com/c/htU2PU4K/1068-restore-not-working-if-we-drag-a-block-to-the-garbage-bin
=> [Restore] Add locale for restore block

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
Ref: https://trello.com/c/wWKGOeJw/1101-when-using-3d-gizmos-copy-the-values-to-blocks-in-the-flyout#comment-61b762269d6c931842d1a70c
=> add locale for rotate to 2

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
Ref: https://trello.com/c/W9Azpy9K/1013-new-method-for-3d-avatar-using-https-readyplayerme
=> Add locale for add avatar for user block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json
https://trello.com/c/F3zGfNBu/1114-adjust-the-logo-image
=> Update logo name

editor/interface/am.json, editor/interface/az.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/is.json, editor/interface/lv.json, editor/interface/vi.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves https://trello.com/c/3p2VZ9KW/1135-update-crash-message
* Look in …
=> update crash message

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json, editor/paint-editor/en.json, editor/paint-editor/es.json, editor/paint-editor/fr.json, editor/paint-editor/zh-cn.json, editor/paint-editor/zh-tw.json
https://trello.com/c/SLzKJyQ4/938-new-spec-for-2d-rigging-tool
=> [Spine] Translations

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/MOorL8sP
Add auto cleanup translate
* Look in …
=> Add auto cleanup translate

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/pUPP3bcD/1175-copy-some-turn-blocks-from-jr-to-full-version
* NOTE: we are moving away from using the `tx` cli; `.tx/config` will eventually be …
=> Add backward block

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
=> Add key pressed translation

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- **Resolve**: https://trello.com/c/rcSvPWCt 
- **Description**  Please modify the "update scale" block to accept 2 more parameters, so it is "update scale x % y % z % in ( ) seconds [Blocking/Non-Blocking]. 
- **Result** 
https://user-images.githubusercontent.com/86275790/150723103-9e14f221-69a6-4327-a072-612ba2991d1d.mp4
=> Add locale for update scale block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/MOorL8sP
- Add vertical mode title
* Look in [https://unpkg.com/react-intl/locale-data/](https://unpkg.com …
=> Enhance - Vertical mode title

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
[#1053](https://trello.com/c/Si4daSXG/1053-a-new-ai-category)
- Add speed and pitch param in text to speech block
=> add speed and pitch param in text to speech block

editor/blocks/ab.json, editor/blocks/af.json, editor/blocks/am.json, editor/blocks/an.json, editor/blocks/ar.json, editor/blocks/az.json, editor/blocks/be.json, editor/blocks/bg.json, editor/blocks/bn.json, editor/blocks/ca.json, editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/vi.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
=> Update new translation new block

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/P4D1PkYD/1207-widgets-update
* Look in …
=> Enhance widget dropdown menu

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/etkxGoDG/1208-a-new-control-block-break
* Look in …
=> Add control block break

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves: https://trello.com/c/Hn3fusN5/1201-more-programming-quiz-requests
* Look in …
=> Enhance secret sprite

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/etkxGoDG/1208-a-new-control-block-break
* Look in …
=> Add continue block

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
https://trello.com/c/F6ddRMPY/1150-regular-expression-operators
Add translate for regex blocks
* Look in …
=> Enhance - Add regex blocks translation

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves: https://trello.com/c/NXCeK50K/1240-a-new-extension-automation-not-premium-available-to-all-users
* NOTE: we are moving away from using the `tx` cli; `.tx/config` will …
=> Enhance automation

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/J0EQ4nwd
- Add translate for olympic toggle and block
* Look in …
=> Feature - Olympic page

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/upt4fIIt/1320-a-trim-operator
* Look in …
=> add "OPERATOR_TRIM "

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves: https://trello.com/c/8IQXuwBd/1210-change-size-fields
* Look in …
=> Add size field

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
[#1354](https://trello.com/c/ffWHMGRA/1354-change-logo-everywhere)
- Adjust new logo
=> adjust new logo

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/dLew1SEw/1361-broadcast-cloud-message-doesnt-work
* …
=> Enhance world

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
[#1243](https://trello.com/c/apa8WG4M/1243-read-pixel-color-in-automation-category)
- Add new block read pixel color
=> Adding Feature Automation Read Pixel Color

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/OaQj1ehw/1421-turn-around-another-sprite
* Look in …
=> Remove blocking input in block turn around

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
Resolves
https://trello.com/c/TO6MKISv/1462-update-switch-to-full-screen-block
Des
please add a new dropdown with 2 choices, so it is "switch to full screen <with border/no border>". The "with border" option is the default, which will be the current function.
The "no border" option is new, which will switch a truly full screen mode so we do not show the browser tab or the frame around the stage. Essentially we just need to make the div that contains the canvas full screen like this example:
https://playground.babylonjs.com/#S1UM5V
However, there is one complication that we have multiple divs for 3D and 2D and video, so they all need to be full screen. maybe we can just make their common parent div full screen?
=> add lang for switchFullScreen block

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/az2HA5gA/1496-youtube-widget-seek-to-time-and-current-time
=> Add language for Youtube widget

editor/interface/zh-tw.json
- Resolves : https://trello.com/c/PDqNpyn2/1565-in-chinese-mode-change-my-variable-to-chiniese-for-new-projects
=> change my variable to chinese language

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/z80tNgLc/1573-youtube-widget-player-new-blocks
1. new block "set volume to ( )"
2. new block for "set playback speed ratio ( )", with 100 as the normal rate and default value, 200 will be double the rate.
thanks
=> feat(widget blocks): new youtube player blocks

editor/blocks/es.json, editor/blocks/fr.json
https://trello.com/c/sBCCqxBa/1591-our-flyout-is-broken-in-french
=> fix(operator blocks) our flyout is broken on french, spanish

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/H8nDcY1E/1577-new-widget-block-set-transparency
"set transparency to ( )% in ( ) seconds"
like set transparency to 0 in 2 seconds, will fade the widget in 2 seconds.
https://user-images.githubusercontent.com/86275790/188551932-831acab4-7cde-450d-b2ad-5c22eaad5ef5.mov
=> feat(widget blocks): new transparency block

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/OMOGxilB/1523-change-some-premium-categories
Small fix: Add translation for warning message
=> enhance(premium blocks): Add translation for warning message

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
https://trello.com/c/t6cURNIv/1628-new-openai-gpt3-block-in-the-ai-category-premium-only
It will be a reporter block: "OpenAI GPT-3: (PROMPT) (MAX_TOKENS)". Basically, it takes any text prompt as the first input, and a character limit on the returned text as the second input (by default 256 and cap at 2048), and it returns a text as the reporter value.
To implement it, we send a request by posting a JSON object to 
https://api.openai.com/v1/completions
I'm not sure how to send the API_KEY when posting a JSON from within the browser using the "Authorization: Bearer" method. Here is an example that uses curl to post the JSON from server side. Maybe it helps?
curl https://api.openai.com/v1/completions \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer …
=> feat(AI category): OpenAi block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves #
https://trello.com/c/OaHEMb7y/1679-empty-holes-for-input-in-blocks
* Look …
=> fix(): add manual fix project

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves #https://trello.com/c/wfIUzqg9/1665-new-updates-to-the-cloud-category-for-working-with-worlds
* NOTE: we are moving away from using the `tx` cli; `.tx/config` will …
=> fix(): Enhance cloud blocks

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
https://trello.com/c/IuJ94brF/1725-new-ai-block-for-openais-image-generator
- add translations for openAI create image error
* …
=> Enhance - OpenAI Create Image error handler

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json
- Resolves #
- https://trello.com/c/W7Y1HVhv/1773-new-block-for-locking-view-port-position
* NOTE: we are moving away from using the `tx` cli; `.tx/config` will eventually be …
=> feat(): attach sprite to viewport

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json
- Resolves #
- https://trello.com/c/RjAQIF0U/1783-viewport-x-and-viewport-y
* Look in …
=> feat(): viewport position block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
[#1815](https://trello.com/c/yh4hpzOl/1815-getting-missing-translation-erros)
- Hotfix : getting missing translation erros
=> hotfix missing message

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/vf2tVvmt/1830-new-widget-block-progress-bar
=> feat: add progressBar widget block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves: https://trello.com/c/oKge7ajC/1846-add-new-explosion-sounds
=> feat: add exposion sounds category

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
https://trello.com/c/EFo9hGv2/1852-3-improvements-to-leaderboard
* Look in …
=> fix(): update game leader board

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves #
- https://trello.com/c/ks09TpT8/1918-add-2-more-blocks-for-table-to-hide-and-show-it
=> feat: add show and hide blocks for table variable

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- [#1921](https://trello.com/c/ckMUm6zs/1921-comment-block)
- Handle add my block comment
=> Handle add my block comment

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/ZUp7Z6LN/1941-widget-name-dropdown-automatic-list
=> enhance: menu control widget

scripts/index-translate.js
- Resolves #
* Look in [https://unpkg.com/react-intl/locale-data/](https://unpkg.com/rea …
=> optimize loading time 2

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/MjGJg6d7/1932-2-new-widgets-for-adding-image
=> feat: add image widget blocks

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- [#2003](https://trello.com/c/hiJTTrxK/2003-add-avatar-for-user)
- Validate default d3 user avatar
=> validate default d3 user avatar

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
-  [#2069](https://trello.com/c/HKCeBNn1/2069-classta-account-blocked-for-chatgpt-urgent)
- Enhance student permissions
=> add student permission error message

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves : https://trello.com/c/mIVrWeNj/2080-save-and-load-data-in-table-urgent
=> feat: create save and load table variables blocks

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
https://trello.com/c/civhoXBu/2100-load-the-shared-avatars-of-another-user-urgent
- Add user avatar block translate
* Look in …
=> Enhance - Add user avatar

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves https://trello.com/c/JtkiMrPt/1997-new-free-ai-blocks-using-webapi
Description: add two blocks.
- using SpeechRecognition() web api.
- using SpeechSynthesis web api
=> feat: web api recognize

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- https://trello.com/c/QGXfV6WD/2106-web-api-text-to-speech-giving-the-same-sound
- Description fix voice default in web API speech block
=> fix: webApi say block

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- [#2129](https://trello.com/c/dQEoFPSk/2129-disable-chatgpt-blocks-in-us-site-for-chinese-users-urgent)
-  Block chatGPT with chinese user
=> feat(): translate block chinese user message

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- [#2166](https://trello.com/c/5K6U7V1F/2166-add-a-new-block-under-cloud-to-load-all-available-worlds)
- Add read world info block
=> feat(): add read world info block translate

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/4WqL8vv3/2201-for-each-3d-object
=> fix(): for each 3D object block

scripts/index-translate.js
https://trello.com/c/iQA5CrMM/2177-block-search-missing-join#comment-653a745a89dcf0d5b497ae5c
- Enhance index translate detect camel case string
* NOTE: we are moving away from using the `tx` cli; `.tx/config` will …
=> Enhance - Index translate key with continuous uppercase letters

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves : https://trello.com/c/Yy8LSjho/2122-chatgpt-system-request-add-temperature
=> enhance(): add temperature params to chatgpt system block

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves https://trello.com/c/n8TtRBBf/2252-new-widget-block-for-camera
=> feat(): widget camera

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves: https://trello.com/c/TNCyvtqS/2257-draw-polygon-in-the-looks-category
=> fix(): draw polygon

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves #
* Look in [https://unpkg.com/react-intl/locale-data/](https://unpkg.com/rea …
=> feat(): new quizzes

editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- [#2159](https://trello.com/c/Xzb2j0PY/2159-move-the-google-sheets-blocks-to-the-cloud-category)
- Move google sheet block from data to cloud category
=> Move google sheet block from data to cloud category

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves #
* Look in [https://unpkg.com/react-intl/locale-data/](https://unpkg.com/rea …
=> feat()--add-gen-image-url-block

editor/interface/en.json, editor/interface/es.json, editor/interface/fr.json, editor/interface/zh-cn.json, editor/interface/zh-tw.json
- Resolves : https://trello.com/c/3VVwq4pj/2376-ai-background-library-and-generation
=> fix(): add rerun translate

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json
- Resolves : https://trello.com/c/SdKxhCkU/2333-rest-apihigh-priority-database
=> feat(): move database apis

editor/blocks/en.json, editor/blocks/es.json, editor/blocks/fr.json, editor/blocks/zh-cn.json, editor/blocks/zh-tw.json, editor/extensions/en.json, editor/extensions/es.json, editor/extensions/fr.json, editor/extensions/zh-cn.json, editor/extensions/zh-tw.json
- Resolves: https://trello.com/c/PS70XriJ/2382-a-new-chatgpt-block-for-image-input
=> feat(): attach image to chat gpt
